### ISSUE TITLE
X360 Xplorer Double Inputs

### ISSUE THREAD

**Issue by Charlster** [InvoxiPlayGames/FestivalInstrumentMapper#11]
Mentioned this on twitter but I'm getting double inputs when using the Xplorer controller. I've tried installing and enabling the HidHide option under the 360 controller hiding link but unplugging and plugging back in the guitar after either clicking the tick or done then start mapping does not fix the double input issue. I've tried restarting the PC but this also didn't seem to make a difference. I'm also on Windows 11 in case that makes a difference.

**Comment by oz1x** [comment]
Can you check what version of Windows 11 you are running? You can see from Settings > System > About. For me, I was an update behind (22H2 instead of 23H2), and am installing update 23H2 through the Windows 11 Install Assistant right now since it wasn't showing up as an available update for me. Will update back if this fixes the HIDHide fail issue.

**Comment by Charlster** [comment]
Yeah I'm on Win11 Home 23H2, let me know how it goes on your end.

**Comment by oz1x** [comment]
dang! was hoping that would fix it. Will do some more experimenting and report back if I figure anything out o7

**Comment by Charlster** [comment]
Tried messing around with a few things earlier today, unplugging the controller, not unplugging the controller., reinstalling hidhide etc but still get the same issue. It seems that hidhide simply isn't doing anything once I tick that box.

**Comment by oz1x** [comment]
Hi Charlester, 

I found a fix for this that might work for you. To try it out, do these steps:

1.) Open up the CLI for HIDHide (fC:\Program Files\Nefarius Software Solutions\HidHide\x64\HidHideCLI.exe for me)

2.) Do --dev-gaming. Note the USB and HID addresses for your 360 guitar (listed as deviceInstancePath and baseContainerDeviceInstancePath), in my case there were two instances of my Xplorer so I noted the USB and HID addresses of both.

![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/97770246/1b4fdc82-f5fb-4c63-8588-4ecf0637f462)
![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/97770246/d69a0070-85c1-4308-914b-6d623fba70c5)


3.) For each address (USB and HID), do a --dev-hide YourAddressGoesHere.

4.) Once all of your addresses are added, do a --app-reg "Path\To\Your\FestivalInstrumentMapper.exe". This will allow the mapper to see your controller.

press Control-Z in the CLI, then hit enter to save your changes and exit.

After doing this I no longer encounter double inputs and can use Pro Lead / Bass without issue!

**Comment by Charlster** [comment]
Hey oz1z,

Just tried this method like you said. After using Control-Z to save the CLI I opened Festival Mapper and the device did not show, even after replugging the device in. The only way to get the guitar to show was to tick the box under setup xbox 360 controller hiding but I'm guessing this just overwrites everything done in the CLI so when pressing Start Mapping and launching the game I still get the double input issue.

**Comment by oz1x** [comment]
Did you make sure to add the festivalinstrumentmapper.exe to the app whitelist? I have it in my downloads folder, so for me the command was:

--app-reg E:\Downloads\FestivalInstrumentMapper.exe

Try repeating the steps and make sure you have done this. After doing that step, try using the command --app-reg to ensure it has been added to the list. you can also do --cloak-state and --dev-list to ensure the cloak is active and the right ids are present.

Let me know if you get the same issue after trying it again!

**Comment by Charlster** [comment]
Hey again,

Just tried again and this time managed to get the guitar to show up on festival mapper once I'd inputted everything correctly (looks like one of the HID lines I copied was from the wrong device). Anyway double checked everything, saved and opened fortnite mapper, clicked start mapping and the game was still double inputting when it launched. Also tried ticking the 360 controller hiding but same double input occurs.
![HidHide CLI Screenshot](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/54869692/d124e5ba-6519-4de7-b4c2-29dc342ec519)

**Comment by oz1x** [comment]
The last thing I can think of would be to make sure you unplug and replug your guitar after saving and closing the CLI tool but before clicking "Start Mapping". Also, make sure you don't click the builtin 360 hiding button on the mapper app, since it will override your config.

**Comment by Charlster** [comment]
So I tried again with no luck, tried restarting the PC but noticed all of the USB names had changed. After resetting them to the new games I booted the game with the mapper on and it just showed as a normal 360 controller. I then opened CLI backup and realised when enabling the mapper it seems to change all of the IDs every time. Meaning whatever I set it to manually is incorrect once I hit start mapping as it seems to add another HID-compliant game controller inbetween the two Guitar (Guitar X-plorer) options each time. The image is what the CLI looked like after attempting to start mapping with the dev list I had setup after rebooting my PC at the bottom.
![HidHide CLI Screenshot](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/54869692/c1a8e819-5035-4e1e-9692-eddb4f201197)

**Comment by Charlster** [comment]
Hi oz1x,

So Emma posted a fix for 360 controllers when fortnite is installed on a different drive than the C Drive, which in my case it was. This has now fixed my issue so I'm gonna close this out. Thanks for all of your help the past couple of days!
