### ISSUE TITLE
WiiTarThing + FIM causes sporadic controller activity

### ISSUE THREAD

**Issue by DigiDuncan** [InvoxiPlayGames/FestivalInstrumentMapper#134]
When using WiiTarThing with FestivalInputMapper, the game will rapidly swap between keyboard and controller inputs, and even two different controllers seemingly, until the point where the Whammy bar is held at ~50%. Even when it is (which as you can imagine is annoying to do and operate the game), when on the stage screen and attempting to play the game, the controls will rapidly change control schemes, dropping most inputs and tanking the frame rate of the game.

**Comment by noobdealer** [comment]
Try using the "Xbox 360 controller hiding" feature, worked for me

**Comment by DigiDuncan** [comment]
> Try using the "Xbox 360 controller hiding" feature, worked for me

This solves the problem! Thank you, closing.
