### ISSUE TITLE
PS3 Logitech (and others) guitars not properly working

### ISSUE THREAD

**Issue by MiseryMachineFN** [InvoxiPlayGames/FestivalInstrumentMapper#14]
this program doesn't seem to work with my PS3 guitar? (It's a Logitech wireless PS3 guitar). it is recognized as a PS3 Guitar, but when i click "start mapping" it instantly shows as "Mapped", and as soon as i press orange, it acts like a "disconnect" command... The rest of the buttons do nothing and it's not recognized on Fortnite at all... i've seen a few folks having the same trouble with PS3 guitars so it has something to do with that console only... One thing that caught my attention is that as soon as the guitar is "mapped" when i press some stuff on my windows it acts like it's constantly pressing up on the keyboard, for example: If i press my windows key, and try to search for something on the search bar, it will overlap that instruction and start going up on the windows menu for some reason...

I don't know if this means anything or not, but i really hope this helps! Problems aside, thank you for taking care of something fortnite should've done from the start... it's really nice seeing more people being able to play festival pro mode... i wish i was one of those but it's still good that most people is still able to do it... i'll be waiting so you hopefuly can find a fix! 

Some info that might be useful:

-I run SCP server on my PC, but i disabled the drivers and disconnected every single controller... didn't help.
-I'm running windows version 10.0.19042.0
-My windows installation is a "Ghost spectre" version, but i don't think that's a problem
-I already enabled developer mode and restarted, didn't help.

**Comment by TheNathannator** [comment]
Should be fixed for next version already, see #2, #3, #6

**Comment by TheNathannator** [comment]
Should be fixed in Beta 2, gonna close for now to give the other issues more room to breathe. If this is still a problem feel free to re-open!
