### ISSUE TITLE
Lags when i touch any button

### ISSUE THREAD

**Issue by ZetsuKasu** [InvoxiPlayGames/FestivalInstrumentMapper#15]
My games goes from 140 Fps to 20 when i press any button and it keeps flashing when i try to do anything, i can't use menues or play the game properly

**Comment by InvoxiPlayGames** [comment]
What guitar are you using, and for what console?

**Comment by ZetsuKasu** [comment]
I'm playing in a Guitar Hero Aerosmith Les Paul from Xbox 360.

**Comment by ZetsuKasu** [comment]
With the 360 wireless adapter

**Comment by ZetsuKasu** [comment]
https://youtu.be/CgI97owKifI i just uploaded a private video for showing how the game looks. It keeps saying "Change Device"

**Comment by gangunotme** [comment]
similar thing happening with a wii les paul using a retrocultmods v2 adapter: https://youtube.com/shorts/bE1cUUkOC7M

**Comment by ultraviolentz** [comment]
Having the exact same issue on a wired xbox x-plorer

**Comment by CyorgGit** [comment]
Same issue here.

Using a Wii Guitar with WiitarThing and it's also having the same effect.
Pressing a fret makes it have a sudden frame rate drop.
[https://youtu.be/fpE95v7OYl0](https://youtu.be/fpE95v7OYl0)

**Comment by TheNathannator** [comment]
Very weird that this is only happening when pressing a button, I'd expect it to be lagging constantly with how the code works currently. Though I'm not sure why it would be lagging in the first place, either.

**Comment by Untaxed1518** [comment]
Same here, GH3 LP through wiitarthing

**Comment by Untaxed1518** [comment]
Sometimes when I hit buttons I see xbox button prompts, could that be related? I'm also getting doubled inputs

**Comment by gangunotme** [comment]
fixed by setting up xbox 360 controller hiding. likely issue is that the xbox 360 controller aspect of the guitar is interfering with the actual guitar aspect, causing the game to freak out whenever a button is pressed

**Comment by ZetsuKasu** [comment]
> fixed by setting up xbox 360 controller hiding. likely issue is that the xbox 360 controller aspect of the guitar is interfering with the actual guitar aspect, causing the game to freak out whenever a button is pressed

Can you add me on discord and help me with that? pls. My username is zetsucl

**Comment by Untaxed1518** [comment]
> fixed by setting up xbox 360 controller hiding. likely issue is that the xbox 360 controller aspect of the guitar is interfering with the actual guitar aspect, causing the game to freak out whenever a button is pressed

That fixed it for me, I avoided doing that for whatever reason, thanks!

**Comment by gangunotme** [comment]
> > fixed by setting up xbox 360 controller hiding. likely issue is that the xbox 360 controller aspect of the guitar is interfering with the actual guitar aspect, causing the game to freak out whenever a button is pressed
> 
> Can you add me on discord and help me with that? pls. My username is zetsucl

in festivalinstrumentmapper there should be a button that says "set up xbox 360 controller hiding"; if it's not clickable you might need to restart the program. after that it should tell you what to do

**Comment by ZetsuKasu** [comment]
With Gangunotme solution works perfectly fine! I'm gonna close this comment.
