### ISSUE TITLE
PS2 SG support?

### ISSUE THREAD

**Issue by fakekurusu** [InvoxiPlayGames/FestivalInstrumentMapper#16]
Just to ask if PS2 controllers connected via usb adapter are not supported? As most of my ps2 'tars are recognised in Windows and RPCS3 as ps3 controllers, but unrecognised in the application.

Thank you!

**Comment by TheNathannator** [comment]
PS2 guitars are a tricky beast to support, as none of the adapters work in a standardized and consistent way. It's not likely to happen any time soon, if at all; we'd need a generic mapping system just to handle it properly.

The only current way to get them working is to use a Santroller-based adapter in HID mode.

**Comment by fakekurusu** [comment]
I figured as much, but it's not the biggest deal to me anyways.

Again, thank you so much!
