### ISSUE TITLE
360 Warriors of Rock Guitar not working in-game

### ISSUE THREAD

**Issue by monkyrez** [InvoxiPlayGames/FestivalInstrumentMapper#17]
Howdy! I'm running a 360 GH Warriors of Rock Guitar connected through an official Microsoft 360 Wireless Adapter and while I am not getting any errors with the app, once I load in game it seems like Fortnite itself is not seeing it and I can't navigate menus or anything with the guitar. HidHide is working because I can turn it off and FN will see the guitar as a regular Xbox controller just fine. Here's a screenshot of what I'm seeing in the app, which seems like everything should be working as intended. 
![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/168316897/a5a6308d-8bd3-4087-8d12-0800044aa608)

Let me know if I can provide any more info to help y'all!

**Comment by wooperworks** [comment]
do you have "ignore controller input" turned on in game, that might be the issue

**Comment by monkyrez** [comment]
> do you have "ignore controller input" turned on in game, that might be the issue

Nope, double checked to be sure but I don't have that activated and like I mentioned if I disable HidHide it works in-game as a normal Xbox controller. I should also add that the app is detecting input correctly too, if I hit the Guide or Select+Start it stops mapping the guitar as intended so the inputs are definitely being seen there. So whatever the issue is, it's specifically in getting the input over to FN.

**Comment by monkyrez** [comment]
OK, got it working. I checked to see if I had the most recent Windows Update and it seemed like there was a Cumulative Update that I hadn't pulled yet. Don't know if that was actually the reason it started to work, but it seems like that did the trick. At the very least that was the only thing that changed on this reboot I just did versus the other few I tried.
