### ISSUE TITLE
PS2 WT Arduinoed Guitar: Up Strum Opening Menu in Song

### ISSUE THREAD

**Issue by nicco77rams** [InvoxiPlayGames/FestivalInstrumentMapper#18]
I have a PS2 WT guitar that has been arduinoed with a Pi Pico. I use Santroller to program the guitar. Frets, select and start all work well. Down Strum works good, but upstrum opens up the quests and song menu while both in lobby and in song. This forces me to downstrum all strum notes. Video posted in Alec's discord as reference: https://cdn.discordapp.com/attachments/862391034548584468/1233957073767759932/fnf.mp4?ex=662efb94&is=662daa14&hm=821a4e4a4ad0ddbe83469cc32731a487b9ac045167bc37ae8da97a5e441112de&

**Comment by AngelLeyend** [comment]
I had the same issue with Santroller guitar, yeah my guitar is configurated as a HID Controller
![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/66274708/29e31fbc-1f3c-4821-8363-9665fe9f8d4f)

**Comment by TheNathannator** [comment]
I don't think this is an issue on our end, from what I'm seeing on Discord someone else was having the same issue on an Xbox One Riffmaster of all things lol

**Comment by nicco77rams** [comment]
wow that's kinds silly. thank you anyways :3

**Comment by TheNathannator** [comment]
Gonna close for the time being, if the cause is indeed narrowed down to FIM we can re-open it then.
