### ISSUE TITLE
PS3 Guitars not mapping right

### ISSUE THREAD

**Issue by scriptedvirus** [InvoxiPlayGames/FestivalInstrumentMapper#2]
Green and Yellow fret bring up the "Start" and "Select" menus respectively in-game and anything besides the Orange fret seems to do nothing. (Orange fret disconnects the guitar like it's mapped to the PS button). I'm trying to use a Guitar Hero 5 guitar if that helps any.

**Comment by iwtdl** [comment]
I also use a PS3 GH5 guitar and have been getting the same issue.

**Comment by TheNathannator** [comment]
I think I narrowed down the issue, it's an off-by-one error. Should be fixed for the next release!

**Comment by scriptedvirus** [comment]
Thank you!

**Comment by iwtdl** [comment]
> I think I narrowed down the issue, it's an off-by-one error. Should be fixed for the next release!

Appreciate it!

**Comment by TheNathannator** [comment]
Beta 2's out, give a go and see if that fixes the issue.

**Comment by TheNathannator** [comment]
Gonna close for now to give the other issues more room to breathe, if this is still a problem feel free to re-open!
