### ISSUE TITLE
PS3 RB1 guitar constantly disconnecting

### ISSUE THREAD

**Issue by ronkl3** [InvoxiPlayGames/FestivalInstrumentMapper#21]
basicall i click start mapping, firstly it doesn't get recognised, then it randomly disconnects

https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/131434827/80f874d0-efe9-42fe-93af-ef77561b2cda

**Comment by TheNathannator** [comment]
See #2, #3, #6, #14, and try the Beta 2 version that just released.

**Comment by ronkl3** [comment]
thanks a lot! this works perfectly now

**Comment by InvoxiPlayGames** [comment]
glad to hear - have fun playing!
