### ISSUE TITLE
Tips for setting up Ardwiino-based guitars w/ Guitar Configurator?

### ISSUE THREAD

**Issue by judge2020** [InvoxiPlayGames/FestivalInstrumentMapper#25]
Has anyone successfully set up an Ardwiino guitar w/ Guitar Configurator with this tool? 

Simply setting the controller up and mapping it doesn't seem to work.

**Comment by sanjay900** [comment]
Use santroller.

**Comment by judge2020** [comment]
Got it, thank you Sanjay. Wasn't aware that it was out of support.
