### ISSUE TITLE
Application (.exe) won't open

### ISSUE THREAD

**Issue by vincentmashups** [InvoxiPlayGames/FestivalInstrumentMapper#26]
I try running the .exe and it won't open. Tried running as administrator and still not working. Developer mode is on.

**Comment by InvoxiPlayGames** [comment]
Not sure what could be wrong - you might need to manually install the .NET 8 Desktop Runtime from Microsoft: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.4-windows-x64-installer

**Comment by vincentmashups** [comment]
that worked! thanks!

**Comment by InvoxiPlayGames** [comment]
no problem! I've added it to the FAQ so other people running into it will know. have fun!
