### ISSUE TITLE
PS2 Controllers not working

### ISSUE THREAD

**Issue by kahhyl** [InvoxiPlayGames/FestivalInstrumentMapper#28]
Hello, I have a PS2 to USB adapter and tried to connect on 3 different guitars with no luck. I tried with 2 wired and 1 wireless. Are these controllers supposed to be supported?

In case it matters, the guitars are red/black & white/red Gibson SGs and a wireless Kramer

**Comment by TheNathannator** [comment]
They are not supported, no, and they most likely won't be any time soon. PS2 guitars are rather difficult to support without a generic mapping system, as none of the PS2 adapters behave the same. 

(Also see issue #16)

**Comment by WaitlistedJay** [comment]
In theory, wouldn't it be possible to make a program or update allowing any generic controller to be mapped as a RB4 controller for Festival, which would allow PS2 Guitars? I'd imagine it would be similar to how PCSX2 handles mapping controllers as guitars

**Comment by sanjay900** [comment]
Yeah of course, but implementing something like that is a lot of work so it won't be something that is done any time soon

**Comment by TheNathannator** [comment]
It's just a matter of whether or not it's worth it to do so at this time. Festival Instrument Mapper is ultimately meant to be a stopgap with hopes that Festival will have better instrument support sometime soon, but if it becomes apparent that that's not happening any time soon then it can be made a priority.
