### ISSUE TITLE
"Failed to initialise GipSyntheticEx. (0x8007007E)"

### ISSUE THREAD

**Issue by Tibblet** [InvoxiPlayGames/FestivalInstrumentMapper#29]
Hi there! I just downloaded and followed the instructions and upon opening the program I've gotten this message in the status and stats box.

Failed to initialise GipSyntheticEx.
Exception: Unable to load DLL 'GipSyntheticEx.dll' or one of its 
dependencies: The specified module could not be found.
(0x8007007E)
Windows: 10.0.19045.0

Hopefully soon y'all will have figured it out. Tysm in advance!

**Comment by TheNathannator** [comment]
Make sure you extracted every file from inside of the .zip file included in the release.

**Comment by yieldespair** [comment]
![Captura de pantalla 2024-04-28 001232](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/168322373/92762cde-9737-4418-a133-f35cc4b51808)
Same here,i installed a new fresh windows but it doesn't work

**Comment by Branbum** [comment]
Same issue and error code here, also with a new Windows 10 install (10.0.19045.0)

**Comment by Tibblet** [comment]
> Make sure you extracted every file from inside of the .zip file included in the release.

This was my fix! I deleted every file again and redownloaded and extracted.

**Comment by RaulGonzalezPortillo** [comment]
![Captura de pantalla 2024-04-28 121041](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/44589277/e2385372-e62f-4f35-a045-9b6b13e80355)

Same here, even downgraded to 22631.2861, clean install, no modifications.

Tried redownloading and extracting the files again.
