### ISSUE TITLE
PS3 Guitar Hero Controller

### ISSUE THREAD

**Issue by decepticawn** [InvoxiPlayGames/FestivalInstrumentMapper#3]
-Flips between controller and keyboard if you try to switch between
-Red/Blue/DPAD/Sturm do nothing
-Green button is escape
-Yellow opens quests
-Orange unmaps guitar
-Start opens emote wheel

**Comment by TheNathannator** [comment]
I think I narrowed down the issue, it's an off-by-one error. Should be fixed for the next release!

**Comment by TheNathannator** [comment]
Gonna close for now to give the other issues more room to breathe, if this is still a problem feel free to re-open!
