### ISSUE TITLE
Raphnet Wii Les Paul, program says mapped but not working in-game

### ISSUE THREAD

**Issue by Dmncc** [InvoxiPlayGames/FestivalInstrumentMapper#30]
![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/168319840/08c7be8d-3ac6-43a2-babf-3dfd517b2cf8)

**Comment by Dmncc** [comment]
No inputs are detected with the guitar ☹️

**Comment by sanjay900** [comment]
out of curiousity, does the tool detect you hitting start + select?

**Comment by sanjay900** [comment]
Can you please try turning off "D-pad as axes"?

**Comment by Justusis0nline** [comment]
I am also having this same issue

**Comment by Dmncc** [comment]
Yes it detects start + select

![image](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/168319840/c6afc744-1b8d-4b2d-8ec8-5360d715a974)

Turning off D-pad setting doesn't seem to make any difference. Reset adapter does nothing :(

**Comment by sanjay900** [comment]
I don't think the raphnet is the problem here, your game isnt seeing the virtual guitar currently. Can you try restarting your PC?

**Comment by Dmncc** [comment]
PC restarted, should the program be launched prior to opening Fortnite? Should I plug in the raphnet adapter before opening the game?

**Comment by Justusis0nline** [comment]
I tried restarting my pc, doesnt seem to have fixed anything. One thing i noticed is that when in the main menu of the game, down strum works in one very specific circumstance. If you are on the play / no fill etc screen and down strum it will take you down to select what gamemode you want to play

**Comment by jackharpster** [comment]
I am also having this issue. The raphnet adapter also was not even recognized by the program until I had installed the raphnet adapter manager, even though clone hero and JoyToKey could detect it.

**Comment by Dmncc** [comment]
> One thing i noticed is that when in the main menu of the game, down strum works in one very specific circumstance.

I noticed this as well, but I was not sure if it was just a coincidence or accidental mouse movement causing this.

**Comment by patrick0903** [comment]
I believe the problem is a setting in fortnite called "ignore controller input".

I was having this problem and noticed that open was turned on, rendering my guitar useless.

make sure this is turned OFF.

**Comment by jackharpster** [comment]
> I believe the problem is a setting in fortnite called "ignore controller input".
> 
> I was having this problem and noticed that open was turned on, rendering my guitar useless.
> 
> make sure this is turned OFF.

you are amazing, it works now. Thanks so much!

**Comment by Justusis0nline** [comment]
where is this setting?

**Comment by patrick0903** [comment]
> where is this setting?

under "mouse and keyboard"

**Comment by Justusis0nline** [comment]
ah! it works!

**Comment by Dmncc** [comment]
Damn im a dummy
