### ISSUE TITLE
Game freaks out 

### ISSUE THREAD

**Issue by CharlesPCodes** [InvoxiPlayGames/FestivalInstrumentMapper#36]
When I have my 360 Rockband connected, the game tries to switch between controller and keyboard causing a "switch device" issue and lag

**Comment by InvoxiPlayGames** [comment]
Try using the "Set up Xbox 360 Controller Hiding" button in the tool and follow the instructions there

**Comment by CharlesPCodes** [comment]
I tried that not sure if im just not doing it right or its not hiding it

**Comment by joeyballentine** [comment]
Make sure you restart your PC after installing HidHide, it won't actually hide it until you restart

**Comment by InvoxiPlayGames** [comment]
If you're still having this issue where the game is constantly fighting between your 360 guitar and the emulated Xbox One guitar, try the solution I put in #65

**Comment by CharlesPCodes** [comment]
This worked thanks a ton!!

**Comment by CharlesPCodes** [comment]
This worked thanks a ton!
