### ISSUE TITLE
Raphnet Adapter Issue

### ISSUE THREAD

**Issue by Prod1igy** [InvoxiPlayGames/FestivalInstrumentMapper#44]
When playing the game the program maps the back button to the "Tab" keybind in the game and can not activate overdrive when playing the song.

**Comment by Psyql** [comment]
Not being able to activate overdrive is a known limitation right now, see [here](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/wiki/FAQ-and-About#overdrive-doesnt-work-with-my-guitar).

**Comment by InvoxiPlayGames** [comment]
Beta 3 has been released with a feature that lets you remap the Select / Minus button to act as tilt for Overdrive.
