### ISSUE TITLE
360 Wireless Les Paul not working

### ISSUE THREAD

**Issue by xracecar** [InvoxiPlayGames/FestivalInstrumentMapper#5]
The game detects the Les Paul (holding the Xbox button causes the screen to move left and the gyro for the starpower/overdrive moves it up and down respectively) The issue however, is whenever the device is mapped, it doesn't do anything. I noticed that the Les Paul guitar only senses inputs when holding down the Xbox button so that might have something to do with it. Overall, it doesn't work properly and might need some further testing somewhere.

**Comment by InvoxiPlayGames** [comment]
that sounds really weird. does your guitar work just fine in Clone Hero or YARG?

**Comment by xracecar** [comment]
Yeah it does. I've been playing for a few years but it just doesn't seem to work properly with this. I have messed with the Xbox 360 hiding setting but it does nothing, probably still due to the fact that it may just not work with the Les Paul without the Xbox button input.

**Comment by TheNathannator** [comment]
> holding the Xbox button causes the screen to move left

Do you have Steam running currently? This sounds like its default desktop configuration is taking effect, where holding the Xbox button makes it move the mouse with the right stick (whammy/tilt are mapped to the right stick).

**Comment by BXTBYT** [comment]
i have the same problem. ive been troubleshooting for the past 30 minutes doing things that i think can help but my 360 les paul just is registering as a normal xbox controller and nothing else. maybe ill wait for beta 3 and see what happens

**Comment by xracecar** [comment]
Steam was indeed messing with the inputs. After closing Steam, the mapper finally worked, however I am stuck with the "Swap Controller" when i get in game. #10 is pretty much what is happening. I'll close this issue so that one can be resolved properly.
