### ISSUE TITLE
[Feature request] Add support for Arduino custom guitars

### ISSUE THREAD

**Issue by joeyballentine** [InvoxiPlayGames/FestivalInstrumentMapper#50]
First off, thanks for this program. And obviously support for actual guitars should come first.

I just want to make sure that it's on the radar eventually to add support for custom guitars, for example ones that use an Arduino internally. If you need anyone to test support for that at some point, I am able to.

**Comment by InvoxiPlayGames** [comment]
this does support custom guitars, running the Santroller firmware for Pi Pico and Arduinos - or any guitar mapped to show up as a PS3 or Wii guitar (in theory)

**Comment by joeyballentine** [comment]
I don't believe the custom guitar I have is using the Santroller firmware and I don't really want to risk messing it up by installing anything new to it, but I understand if it's just unreasonable to expect something unusual to be supported.

**Comment by joeyballentine** [comment]
😅 that might be a problem because I bought this thing  like 5-6 years ago and I have no idea from who lol

**Comment by sanjay900** [comment]
If you don't want to use Santroller, you should be able to get away with using Guitar configurator and just setting it to PS3 mode.

**Comment by joeyballentine** [comment]
So I did a little digging with @sanjay900 on Discord, and my guitar is seemingly so old it's not using Santroller or Guitar Configurator, but rather some custom code from the modder, and neither program is able to program it/configure it at all. 

So, I guess this issue has just turned into "please add support for any random input device".

**Comment by InvoxiPlayGames** [comment]
you might be able to use x360ce version 3 (x64), with xinput1_4.dll in the FestivalInstrumentMapper folder, to get the tool to detect your guitar as an Xbox 360 Guitar, and use it that way. otherwise, it's not really in-scope to add manual input re-mapping

**Comment by joeyballentine** [comment]
Thanks, will try
