### ISSUE TITLE
Rockband 3 Pro Wireless Guitar for PS3 not detected by program

### ISSUE THREAD

**Issue by Hollexian** [InvoxiPlayGames/FestivalInstrumentMapper#52]
I have this guitar https://www.amazon.com/Wireless-Mustang-PRO-Guitar-Controller-PlayStation-3/dp/B003RS1A7Y and have it connected to the PC through a wired MIDI cable. The mapper doesn't detect the connected guitar.

**Comment by GrayHefe** [comment]
Why are you trying to use that?

**Comment by Hollexian** [comment]
> Why are you trying to use that?

Because it's the one I have.

**Comment by InvoxiPlayGames** [comment]
sadly because of how complex they are I can't support the PS3 / Wii Rock Band 3 Pro guitars, or any guitars connected over MIDI, sorry

**Comment by Hollexian** [comment]
> sadly because of how complex they are I can't support the PS3 / Wii Rock Band 3 Pro guitars, or any guitars connected over MIDI, sorry

I know it's a long shot, but RPCS3 (PS3 emulator) is open source and has support for midi guitars. I'll look into implementing it myself but just wanted to let you know
