### ISSUE TITLE
"Failed to initialise GipSyntheticEx. (0x8007007E)"

### ISSUE THREAD

**Issue by RaulGonzalezPortillo** [InvoxiPlayGames/FestivalInstrumentMapper#59]
Sorry for bringing this up again, Tibblet got their issue solved and closed it, unfortunately I'm having no luck running the program at this time.

![Build 22631 2861](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/44589277/0ceba20d-8a71-40fd-8ed8-12de8df9e440)

![Build 22631 3447](https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/44589277/f7614b2a-210f-4dca-87d2-72cf2a2b7a22)

I've already tried reinstalling Windows a few times, trying different builds to see if this behavior changes. These were clean Windows 11 Pro reinstalls, no modifications other than installing .NET 8.

Builds tested:
22621.382 - Error 0x8007007E
22631.2861 - Error 0x8007007E
22631.3447 - Error 0x8007007E
26100.1 - Error 00000001 (Same as issue #41)

Other things I've tried:
- Grabbing xboxgipsynthetic.dll from another computer I have that can run the program and putting it in the same folder, same result.
- Updating all Xbox related services.

Let me know if there's anything I can do to make a more useful report.

**Comment by Branbum** [comment]
Same issue here also on a very clean windows 10 install (10.0.19045.0). Saw someone say they fixed it by uninstalling and reinstalling making sure everything is unzipped, done it about 30 times with no difference.

**Comment by InvoxiPlayGames** [comment]
Try installing the visual C++ redistributable from Microsoft https://aka.ms/vs/17/release/vc_redist.x64.exe

It should be pre-installed on Windows to my knowledge, but maybe it isn't?

**Comment by Branbum** [comment]
This was it for me!! Thank you! I just did a fresh install the other night because i was on a Win11 Insider Dev build and it was giving me issues so i finally switched. The redistributable was not already installed for me at least, although i haven't downloaded my steam games back which downloads them sometimes I believe

**Comment by InvoxiPlayGames** [comment]
Glad to know it works! I'll add it to the FAQ and About page, and if this works for OP as well, I'll close this issue
