### ISSUE TITLE
Wii Wireless Rock Band 2 Guitar not working correctly

### ISSUE THREAD

**Issue by bruhmoment69420** [InvoxiPlayGames/FestivalInstrumentMapper#6]
Its able to be mapped, but after a few button presses it unmaps itself.

https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/assets/53867821/01cce0f5-0a19-4561-8b29-0848b66de3cb

**Comment by TheNathannator** [comment]
Should be fixed for next version, same issue that was affecting PS3 guitars.

**Comment by TheNathannator** [comment]
Gonna close for now to give the other issues more room to breathe, if this is still a problem feel free to re-open!
