### ISSUE TITLE
Overdrive not bound with Santroller

### ISSUE THREAD

**Issue by JakeHRobinson** [InvoxiPlayGames/FestivalInstrumentMapper#60]
I eventually got it working using Santroller, it's now all recognised ingame. Not sure if it's a binding issue on my end, though I've reset controller binding to default in fortnite and I don't see binding options for pro lead, but I'm unable to use overdrive. When I press star power it brings up a songlist menu thing? I'm also able to see my quests in there. Not entirely sure what menu it's bringing up but I'm completely unable to use overdrive. 

It's a pico modded World Tour if that makes any difference, not that it should.

**Comment by gozfrt** [comment]
yes because Fortnite has somehow binded Overdrive to Left Dpad instead of Select/OD/Star Power. It sometimes work just by pressing Select and sometimes it doesnt

**Comment by InvoxiPlayGames** [comment]
Beta 3 has been released with a feature that lets you remap the Select / Minus button to act as tilt for Overdrive.
