### ISSUE TITLE
Worked once and then never again (Xbox 360 les paul unmodded guitar)

### ISSUE THREAD

**Issue by SchneiderAFX** [InvoxiPlayGames/FestivalInstrumentMapper#62]
As the title implies, this worked fine the first time i tried it but, for some reason, the next day I'm unable to make it work with Fortnite. The program itself detects the guitar and mapped it just fine (i can enable and disable it pressing the start and select button), but Fortnite refuse to detect it (i have the "ignore controller input" option disabled and everything).

**Comment by monkyrez** [comment]
I have a similar issue that I reported in #17 I wasn't able to get it working at first when the app came out yesterday, after forcing a Windows Update and restarting it magically started working and I played quite a bit but after powering my PC back up and trying again to play today that I'm back to having the same issue where the FIM sees the guitar just fine, but the inputs seemingly aren't passed to FN (I also don't have ignore controller input set to On).

**Comment by Babyneedssocks** [comment]
Same problem for me but with a 360 xplorer. Worked the first time but after I reset my computer to update nothing is recognized in fortnite. Been messing around with inputs for a while and nothing else is using the controller so not quite sure.

**Comment by Babyneedssocks** [comment]
Solved it! So either Fortnite or the tool need the 360 “controller” to be Player 1. Basically troubleshooting by unplugging, resetting etc will create new drivers each time so you have to delete them in the hidden files in device manager, reset pc while the guitar is plugged in. That works for now at least

**Comment by SchneiderAFX** [comment]
> Solved it! So either Fortnite or the tool need the 360 “controller” to be Player 1. Basically troubleshooting by unplugging, resetting etc will create new drivers each time so you have to delete them in the hidden files in device manager, reset pc while the guitar is plugged in. That works for now at least

tried that and still no luck, i don't know if I'm doing something wrong because i disabled the hidden controllers on device manager
