### ISSUE TITLE
Overdrive for wii guitar using RetroCult adapter

### ISSUE THREAD

**Issue by MichaelAtkin316** [InvoxiPlayGames/FestivalInstrumentMapper#68]
sometimes it wants to work and sometimes it just doesnt idk if there is a fix if so plz help

**Comment by NoobiBoobi** [comment]
This is a known issue.

**Comment by InvoxiPlayGames** [comment]
Beta 3 has been released with a feature that lets you remap the Select / Minus button to act as tilt for Overdrive.
