### ISSUE TITLE
Input issue on wii guitar

### ISSUE THREAD

**Issue by Scum2EViL** [InvoxiPlayGames/FestivalInstrumentMapper#72]
using a 3rd party wii guitar, shows up as xbox 360 gamepad (1), everything works fine expect for green and red being swapped, anyone know a fix?

**Comment by InvoxiPlayGames** [comment]
How are you connecting the guitar to the PC?

**Comment by Scum2EViL** [comment]
Connected through raphnet, cheap replica guitar so im sure that doesn't help, doesn't pop up on wiitar, thinking about using xbox360ce just don't know what binds to use with the festival mapper, other than the frets being swapped, I have no other issues

**Comment by InvoxiPlayGames** [comment]
I'll have to look into it in the future, in the meantime here's mappings for x360ce:
- Green Fret = A
- Red Fret = B
- Yellow Fret = X
- Blue Fret = Y
- Orange Fret = Left Bumper
- Up Strum = D-Pad Up
- Down Strum = D-Pad Down
- Minus = Back
- Plus = Start

**Comment by Scum2EViL** [comment]
Switching binds one xbox360ce fixed my issue, thank you 👍
