### ISSUE TITLE
Wii guitar using WiitarThing not working

### ISSUE THREAD

**Issue by ShadowWolf962** [InvoxiPlayGames/FestivalInstrumentMapper#88]
Ive been trying to get this set up to work with FN festival but no matter what i do, nothing seems to be detected in Fortnite. Ive tried using all 3 betas of the mapper software, it says everything should be working, but once im ingame no pro options show up nor do the controls. Ive tried using different wiitar versions, reinstalled drivers, updated windows to newest windows 10 version. The only sign of it working is if i spam some buttons as Fortnite loads into the main menu it shows it up for a split second, unlocking the pro modes but then never recognizes again. If anyone can help out please lmk!

**Comment by HelloGoobie** [comment]
It worked straight away for me using the latest Wiitarthing and the latest FestivalInstrumentMapper.
Make sure you don't have the "ignore controller input" toggled
