### ISSUE TITLE
Swap Overdrive to Select not working

### ISSUE THREAD

**Issue by SrBaguette** [InvoxiPlayGames/FestivalInstrumentMapper#89]
Hello, the program is working well but I have an issue with the swap overdrive button, if I activate the option nothing happens and the star power button doesnt do anything at all, at some point (I disabled the option and it kinda worked for some reason) I was able to use the select button to activate overdrive but at the same time it opened the Festival menu.

Any way to solve this? I'm using a Guitar Hero 5 Wii Guitar via WiitarThing.

Also thank you a lot for creating the tool, you're awesome :D

**Comment by SrBaguette** [comment]
Nvm I fixed it, it seems that for some reason if you have a Play Station controller connected and the gyro aim activated the Tilt function of the guitar will not work. lol

Disabled gyro aim and now it works as intented.

**Comment by InvoxiPlayGames** [comment]
Thanks for providing a fix, I'll update the FAQ. Glad you're enjoying it!
